_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 10
max_epochs: 100

weights_summary: top
progress_bar_refresh_rate: 5

terminate_on_nan: True
