_target_: src.models.graph_classifier.GraphClassifier
architecture: GCN
optimizer: adam
lr: 0.001
weight_decay: 0.0005
node_features: ${datamodule.num_node_features}
classes: ${datamodule.classes}
conv1_size: 32
conv2_size: 64
conv3_size: 512
pool_method: "max"
lin1_size: 64
dropout1: 0.25
