_target_: src.models.graph_classifier.GraphClassifier
optimizer: adam
lr: 0.001
weight_decay: 0.0
architecture: GCN
activation: "relu"
node_features: ${datamodule.node_features}
conv1_size: 64
conv2_size: 128
conv3_size: 512
pool_method: add
lin1_size: 128
lin2_size: 64
output_size: ${datamodule.classes}
