_target_: src.datamodules.mnist_superpixels.MNISTSuperpixelsDataModule
data_dir: ${data_dir}
batch_size: 64
train_val_test_split: [55_000, 5_000, 10_000]
node_features: 1
classes: 10
pin_memory: False
num_workers: 0