model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val_acc"      # name of the logged metric which determines when model is improving
    save_top_k: 1           # save k best models (determined by above metric)
    save_last: True         # additionaly always save model from last epoch
    mode: "max"             # can be "max" or "min"
    filepath: "checkpoints/{epoch}"


early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val_loss"     # name of the logged metric which determines when model is improving
    patience: 5             # how many epochs of not improving until training stops
    mode: "min"             # can be "max" or "min"
    min_delta: 0.0          # minimum change in the monitored metric needed to qualify as an improvement


upload_code_to_wandb_as_artifact:
    _target_: src.callbacks.wandb_callbacks.SaveCodeToWandb
    code_dir: ${original_work_dir}/
