GRAPH_CLASSIFIER_MNIST_150:
    trainer:
        max_epochs: 5
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
        limit_train_batches: 1.0
    model:
        model_folder: "graph_classifier"
        lr: 0.001
        weight_decay: 0.000001
        num_node_features: 3
        num_classes: 10
        pool_method: "mean"
        conv1_size: 64
        conv2_size: 64
        conv3_size: 32
        lin1_size: 128
    dataset:
        datamodule_folder: "mnist_superpixels_150"
        batch_size: 64
        train_val_split_ratio: 0.9
    wandb:
        group: None
        tags: []


GRAPH_CLASSIFIER_MNIST:
    trainer:
        max_epochs: 5
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
        limit_train_batches: 1.0
    model:
        model_folder: "graph_classifier"
        lr: 0.001
        weight_decay: 0.000001
        num_node_features: 1
        num_classes: 10
        pool_method: "mean"
        conv1_size: 64
        conv2_size: 64
        conv3_size: 32
        lin1_size: 128
    dataset:
        datamodule_folder: "mnist_superpixels"
        batch_size: 64
        train_val_split_ratio: 0.9


IMG_CLASSIFIER_MNIST:
    trainer:
        min_epochs: 1
        max_epochs: 3
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
        limit_train_batches: 1.0
    model:
        model_folder: "simple_mnist_classifier"
        lr: 0.001
        weight_decay: 0.000001
        input_size: 784
        output_size: 10
        lin1_size: 256
        lin2_size: 256
        lin3_size: 128
    dataset:
        datamodule_folder: "mnist_pixels"
        batch_size: 64
        train_val_split_ratio: 0.9
        num_workers: 1
        pin_memory: False
    resume_training:
        checkpoint_path: "logs/wandb/run-20201201_041527-7ab26xrj/files/tests/7ab26xrj/checkpoints/last.ckpt"
        wandb_run_id: "7ab26xrj"
