MNIST_CLASSIFIER_V1:
    trainer:
        max_epochs: 5
        gradient_clip_val: 0.5
    model:
        model_folder: "simple_mnist_classifier"
        lr: 0.001
        weight_decay: 0.000001
        input_size: 784  # img size is 1*28*28
        output_size: 10  # there are 10 digit classes
        lin1_size: 256
        lin2_size: 256
        lin3_size: 128
    dataset:
        datamodule_folder: "mnist_digits_datamodule"
        batch_size: 64
        train_val_split_ratio: 0.9
        num_workers: 1
        pin_memory: False


MNIST_CLASSIFIER_V2:
    trainer:
        min_epochs: 1
        max_epochs: 10
        gradient_clip_val: 0.5
        accumulate_grad_batches: 2
        fast_dev_run: False
        limit_train_batches: 1.0
        limit_val_batches: 1.0
        limit_test_batches: 1.0
        val_check_interval: 1.0
    model:
        model_folder: "simple_mnist_classifier"
        lr: 0.002
        weight_decay: 0.00001
        input_size: 784
        output_size: 10
        lin1_size: 512
        lin2_size: 256
        lin3_size: 128
    dataset:
        datamodule_folder: "mnist_digits_datamodule"
        batch_size: 256
        train_val_split_ratio: 0.9
        num_workers: 1
        pin_memory: False
    wandb:
        group: None
        tags: ["v2", "uwu"]
    resume_training:
        checkpoint_path: "logs/wandb/run-20201201_041527-7ab26xrj/files/tests/7ab26xrj/checkpoints/last.ckpt"
        wandb_run_id: "7ab26xrj"
