GCN_MNIST_75:
    trainer:
        max_epochs: 50
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
    model:
        model_folder: "graph_classifier"
        lr: 0.001
        weight_decay: 0.000001
        num_node_features: 3
        num_classes: 10
        pool_method: "max"
        conv1_size: 32
        conv2_size: 64
        conv3_size: 512
        lin1_size: 64
        dropout1: 0.25
    dataset:
        datamodule_folder: "mnist_superpixels_custom"
        num_nodes: 75
        batch_size: 32
        val_set_length: 10_000
    wandb:
        group: "sp75"
        tags: []


GCN_MNIST_150:
    trainer:
        max_epochs: 50
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
    model:
        model_folder: "graph_classifier"
        lr: 0.001
        weight_decay: 0.000001
        num_node_features: 3
        num_classes: 10
        pool_method: "max"
        conv1_size: 32
        conv2_size: 64
        conv3_size: 512
        lin1_size: 64
        dropout1: 0.25
    dataset:
        datamodule_folder: "mnist_superpixels_custom"
        num_nodes: 150
        batch_size: 32
        val_set_length: 10_000
    wandb:
        group: "sp150"
        tags: []


BASELINE_PIXEL_MNIST_CLASSIFIER:
    trainer:
        min_epochs: 1
        max_epochs: 3
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
        limit_train_batches: 1.0
    model:
        model_folder: "simple_mnist_classifier"
        lr: 0.001
        weight_decay: 0.000001
        input_size: 784
        output_size: 10
        lin1_size: 256
        lin2_size: 256
        lin3_size: 128
    dataset:
        datamodule_folder: "mnist_pixels"
        batch_size: 64
        train_val_split_ratio: 0.9
#        val_set_length: 10_000
        num_workers: 1
        pin_memory: False
    wandb:
        group: "pixels"
        tags: []
    resume_training:
        checkpoint_path: None
        wandb_run_id: None
