GCN_DD:
    trainer:
        max_epochs: 50
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
    model:
        model_folder: "graph_classifier"
        lr: 0.0001
        weight_decay: 0.000001
        num_node_features: 89
        num_classes: 2
        conv1_size: 32
        conv2_size: 64
        conv3_size: 512
        pool_method: "max"
        lin1_size: 64
        dropout1: 0.25
    dataset:
        datamodule_folder: "dd"
        batch_size: 32
        train_val_split_ratio: 0.9
    wandb:
        group: "dd"
        tags: []


GCN_PROTEINS:
    trainer:
        max_epochs: 50
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
    model:
        model_folder: "graph_classifier"
        lr: 0.0005
        weight_decay: 0.000001
        num_node_features: 4
        num_classes: 2
        conv1_size: 32
        conv2_size: 64
        conv3_size: 512
        pool_method: "max"
        lin1_size: 64
        dropout1: 0.25
    dataset:
        datamodule_folder: "proteins"
        batch_size: 32
        train_val_split_ratio: 0.9
    wandb:
        group: "proteins"
        tags: []


GCN_MNIST_75:
    trainer:
        max_epochs: 50
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
        limit_train_batches: 1.0
    model:
        model_folder: "graph_classifier"
        lr: 0.001
        weight_decay: 0.000001
        num_node_features: 3
        num_classes: 10
        conv1_size: 32
        conv2_size: 64
        conv3_size: 512
        pool_method: "max"
        lin1_size: 64
        dropout1: 0.25
    dataset:
        datamodule_folder: "mnist_superpixels_custom"
        num_nodes: "75"
        batch_size: 32
        train_val_split: [60_000, 10_000]
    callbacks:
        ConfusionMatrixLoggerCallback:
            class_names: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
    wandb:
        group: "mnist_sp75"
        tags: []


GCN_MNIST_150:
    trainer:
        max_epochs: 50
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
        limit_train_batches: 1.0
    model:
        model_folder: "graph_classifier"
        lr: 0.001
        weight_decay: 0.000001
        num_node_features: 3
        num_classes: 10
        conv1_size: 32
        conv2_size: 64
        conv3_size: 512
        pool_method: "max"
        lin1_size: 64
        dropout1: 0.25
    dataset:
        datamodule_folder: "mnist_superpixels_custom"
        num_nodes: "150"
        batch_size: 32
        train_val_split: [60_000, 10_000]
    callbacks:
        ConfusionMatrixLoggerCallback:
            class_names: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
    wandb:
        group: "mnist_sp150"
        tags: []


BASELINE_PIXEL_MNIST_CLASSIFIER:
    trainer:
        min_epochs: 1
        max_epochs: 3
        gradient_clip_val: 0.5
        accumulate_grad_batches: 1
        limit_train_batches: 1.0
    model:
        model_folder: "baseline_pixel_mnist_classifier"
        lr: 0.001
        weight_decay: 0.000001
        input_size: 784
        output_size: 10
        lin1_size: 256
        lin2_size: 256
        lin3_size: 128
    dataset:
        datamodule_folder: "mnist_pixels"
        batch_size: 64
        train_val_split: [60_000, 10_000]
        num_workers: 1
        pin_memory: False
    callbacks:
        ConfusionMatrixLoggerCallback:
            class_names: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
    wandb:
        group: "mnist_pixels"
        tags: []
    resume_training:
        checkpoint_path: None
        wandb_run_id: None
