_target_: src.models.sp_classifier_model.SuperpixelClassifierModel
architecture: GCN
num_node_features: 3
activation: prelu
num_conv_layers: 3
conv_size: 256
pool_method: add
lin1_size: 128
lin2_size: 64
output_size: 10
lr: 0.001
weight_decay: 0
