# trainer args for debugging model
_target_: pytorch_lightning.Trainer

gpus: 0  # set -1 to train on all GPUs abailable, set 0 to train on CPU only
# auto_select_gpus: True

gradient_clip_val: 0.5

#fast_dev_run: True  # bugged :(

min_epochs: 1
max_epochs: 3

# overfit on 10 of the same batches
overfit_batches: 10

#limit_train_batches: 0.1
#limit_val_batches: 0.3
#limit_test_batches: 0.3

#check validation set 2 times during a training epoch
#val_check_interval: 0.5

# check validation set every 1000 training batches
#val_check_interval: 1000

num_sanity_val_steps: 0

progress_bar_refresh_rate: 10

# print full weight summary of all modules and submodules
weights_summary: "full"
#weights_summary: "top"

default_root_dir: "lightning_logs/"
#checkpoint_callback: False

# use profiler to print execution time profiling after training ends
#profiler: "simple"
#profiler: "advanced"
