_target_: pytorch_lightning.Trainer
gpus: 1  # set -1 to train on all GPUs available, set 0 to train on CPU only
min_epochs: 10
max_epochs: 100
gradient_clip_val: 0.5
progress_bar_refresh_rate: 10
weights_summary: "full"
default_root_dir: "lightning_logs/"
num_sanity_val_steps: 0
# benchmark: True
# amp_backend='apex'
