# @package _group_

# Weights&Biases logger config
wandb:
    class: pytorch_lightning.loggers.wandb.WandbLogger
    args:
        project: "graph_classification_benchmarks"
        entity: "lodz"
        offline: False
        job_type: "train"
        save_dir: "."
